config/routes.rb
Rails.application.routes.draw do

  root "orders#index"
  resources :orders

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :product
  belongs_to :warehouse

  def self.locate(product, quantity)
    where("product_id = ? AND quantity >= ?", product.id, quantity).first.try(:warehouse)
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  def increment(qty)
    update(quantity: quantity + qty)
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  has_many :shipments
  has_many :products, through: :line_items

  def add_product(product, quantity=1)
    if line_item = line_items.find_by(product_id: product.id)
      line_item.increment(quantity)
    else
      line_items.create(product: product, quantity: quantity)
    end
  end

  def process
    unadded_items = assign_line_items(Shipment.create(order: self), line_items)

    while unadded_items.count > 0
      unadded_items = assign_line_items(Shipment.create(order: self), unadded_items)
    end
  end

  def self.prioritized
    order('orders.created_at')
  end

  private

  def assign_line_items(shipment, items)
    remainder = []

    items.each do |line_item|
      if shipment.warehouse.nil?
        find_warehouse(shipment, line_item)
      else
        remainder << line_item unless add_to_shipment(shipment, line_item)
      end
    end
    remainder
  end

  def find_warehouse(shipment, line_item)
    if warehouse = Inventory.locate(line_item.product, line_item.quantity)
      shipment.update(warehouse_id:  warehouse.id)
      shipment.add(line_item.product)
      warehouse
    else
      raise Exception.new("This product is not in stock")
    end
  end

  def add_to_shipment(shipment, line_item)
    if shipment.warehouse.has?(line_item.product, line_item.quantity)
      shipment.add(line_item.product)
      true
    else
      false
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :inventories
  has_many :line_items
  has_many :product_shipments
  has_many :shipments, through: :product_shipments
  has_many :warehouses, through: :inventories
  has_many :orders, through: :line_items
end

app/models/product_shipment.rb
class ProductShipment < ActiveRecord::Base
  belongs_to :product
  belongs_to :shipment
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  belongs_to :order
  belongs_to :warehouse
  has_many :product_shipments
  has_many :products, through: :product_shipments

  def add(product)
    products << product
  end
end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  has_many :inventories
  has_many :shipments
  has_many :products, through: :inventories

  
  def has?(product, qty)
    inventories.where("product_id = ? AND quantity >= ?", product.id, qty).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @unprocessed_orders = Order.includes(:shipments).where(shipments: {order_id: nil}).prioritized
    @processed_orders = Order.joins(:shipments).group('orders.id').having('count(order_id) > 0').prioritized
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.create
    params[:order].each do |order|
      product = Product.find(order[:product_ids].to_i)
      @order.add_product(product, order[:line_items].to_i)
    end
    @order.process
    @order.update(destination: params[:order].last["destination"])

    redirect_to action: "index", flash: {notice: "Order created."}
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:destination, product_ids: [], line_items: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Shipment Tracker</li>
      <li>
        <%= link_to "View Orders", orders_path %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Shipment Tracker" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <%= render 'layouts/navigation' %>

  <body>

    <%= yield %>

  </body>
</html>

app/views/orders/index.html.erb
<div class="large-12 columns">
  <h3>Processed Orders</h3>
  <table class="table">
    <tr>
      <th>Order ID</th>
      <th>Number of Shipments</th>
    </tr>
    <% @processed_orders.each do |processed_order| %>
        <tr class="order-link" data-link="<%= order_path(processed_order) %>">
          <td><%= processed_order.id %></td>
          <td><%= processed_order.shipments.count %></td>
        </tr>
    <% end %>
  </table>

  <% if @processed_orders.empty? %>
    None
  <% end %>

  <h3>Unprocessed Orders: <%= @unprocessed_orders.count %> </h3>

  <% if @unprocessed_orders.empty? %>
    None
  <% end %>

  <div style="margin-top: 1rem;">
    <%= link_to "New Order", new_order_path, class: "button" %>
  </div>
</div>

app/views/orders/new.html.erb
<div class="large-12 columns">
  <div class="well">
    <h3 class="header">New Order</h1>
    <%= form_for "order[]", url: orders_path do |f| %>
      <div class="item">
        <div class="product">
          <div>
            <%= f.label :product %>
            <%= f.collection_select :product_ids, Product.all, :id, :name, multiple: true %>
          </div>
          <br>
          <div class="line_items">
            <%= f.label :line_items %>
            <%= f.select :line_items, options_for_select(1..10), multiple: true %>
          </div>
        </div>
      </div>
      <div class="destination">
        <%= f.label :destination %>
        <%= f.text_field :destination %>
      </div>
      <br>
      <br>
      <%= f.submit "Submit", class: "button" %>
    <% end %>
    <button class="button secondary" id="add-button">Add another product</button>
  </div>
</div>

app/views/orders/show.html.erb
<div class="large-12 columns">
  <br>
  <div>
    Order ID: <%= @order.id %>
  </div>
  <h3>Shipments</h3>
  <table>
    <tr>
      <th>Warehouse Number</th>
      <th>Warehouse Location</th>
      <th>Shipment Destination</th>
      <th>Products</th>
    </tr>
  <% @order.shipments.each do |shipment| %>
    <tr>
      <td><%= shipment.warehouse_id %></td>
      <td><%= shipment.warehouse.address %></td>
      <td><%= @order.destination %></td>
      <td><% shipment.products.each do |product| %>
        <ul>
          <li><%= product.name %></li>
        </ul>
        <% end %>
      </td>
    </tr>
    <% end %>

  </table>
</div>